apiVersion: v1
kind: Service
metadata:
  name: url-monitor-service
spec:
  selector:
    app: url-monitor
  type: NodePort
  ports:
    - port: 9000
      nodePort: 30100
      protocol: TCP
      targetPort: url-monitor
